### ISSUE TITLE
検証する仮説の選定

### ISSUE THREAD

**Issue by YusukeShimizu** [YusukeShimizu/LN-ASP#1]
ライトニングネットワークの少額決済でアフィリエイト広告の報酬をアフィリエイターに支払えるようになると、手数料も安くなるし、アフィリエイターは送客するたびに報酬貰えるしで、大きなメリット提供出来るんじゃないか？という仮説検証というところまで決まってますが、もうちょい詰めて行きますか！

**Comment by seiyakitazume** [comment]
アフィリエイト広告とは別の話ですが！

記事広告(ウェブ媒体で記事読んでて最後にPRって入ってる記事です)売ってる時に思っていたのですが、記事広告の拡散をするための広告を打つときに、大体クリック課金なんですよね。
クリックされた後の経過時間で課金出来たらいいなと思いました。ライトニングでそういう事が実装できたら新しい広告商品が出来るかもです。

**Comment by seiyakitazume** [comment]
時間で課金難しそうですね。クリックしたページの先の、ページ閲覧ごとの課金とかなら出来る気がする。

**Comment by seiyakitazume** [comment]
時間単位で決済しているこういうサービスあるみたいですね！
https://btcnews.jp/bitcoin-live-streaming-service-streamium-beta/

**Comment by YusukeShimizu** [comment]
サブスクリプションとかクリック単価とかも時間単位課金に変えられる可能性はありますね
経過時間課金にするなら、どうやって経過時間を計測するかも技術的にむずかしそうではありますが
あとは、終始匿名でアフィリエイター、業者のマッチングできるので、そこも大きなメリットになりますよね

**Comment by seiyakitazume** [comment]
別の話題ですが、これすごい。

■ライトニングとAtmic swapを利用したコイン交換できるウォレット
https://zigzag.bitlum.io/#/

9/8にメインネットにリリースしたみたいです。めっちゃ最近ですね。
https://medium.com/bitlum/zigzag-mainnet-release-7cc111959f90

少額決済と他のコインとの交換が合わさったら、いろんなサービスが広がりそうですね。

**Comment by YusukeShimizu** [comment]
可能だと思いますが、ちょっと作ってみないとですね・・・

**Comment by seiyakitazume** [comment]
そこの技術検証ハッカソンでしたいですね(^^)

あとはアフィリエイターと事業者のペイメントチャネルの開く導線がどこまで簡単に出来るかも大事ですねー！

マルチシグウォレットをアフィリエイターと繋がないとですね。
