### ISSUE TITLE
ワイヤーフレーム作成

### ISSUE THREAD

**Issue by YusukeShimizu** [YusukeShimizu/LN-ASP#2]
イメージ共有のためのワイヤーフレームをアイディアベースでもアップして行ってください。
これをみながら実装もできる範囲からしてしまって、２４日にはある程度部品は揃ってる状態に持っていきたいですね。

**Comment by seiyakitazume** [comment]
**クライアント側のダッシュボード**
機能①アフィリエイターから発生したコンバージョンが、まとめて数値として反映される。
本当のサービスであれば、広告別・時間帯別・媒体別(アフィリエイター別)で表示させたいですが、ハッカソンではただのコンバージョンの数値が反映されているダッシュボードを作りたいです。

機能②コンバージョンを承認するとアフィリエイターへ送金が走る

検討すべき事項：
[1]ライトニングネットワークでは相手がオンラインでないと送金が出来ない。アフィリエイターがオフラインの場合どうするか。
[2]ライトニングネットワークでは送金の失敗が起こることがあるらしい。その場合どうするか。

**アフィリエイター側のダッシュボード**
日別・時間帯別のコンバージョンを計測
クライアントからコンバージョンを承認されて、送金されたbtcを表示。

検討すべき事項：
アフィリエイター側のウォレットを開発しなければいけない。

**その他検討すべき事項**
デポジットが足りなくなるとクライアントが承認したのにアフィリエイターに報酬が払えなくなってしまう。
→デポジットが足りなくなる前に、承認を待ってもらう機能が必要。

デポジットを補充する際、アフィリエイターとペイメントチャネルを開き直す必要がある。
→月1回などアフィリエイターとペイメントチャネルを開く作業が必要になる。

・アフィリエイターとのペイメントチャネルを開くステップが若干煩雑なのでどこまで簡潔に出来るか。
ペイメントチャネルを開くには
①僕らからアフィリエイターと共有のマルチシグウォレットを持ちます
②僕らからマルチシグウォレットへ少額送金し、トランザクションを作る
③トランザクション承認まで10ブロック承認(正確な数は分かりませんが、)など待つ必要がある(ここで数時間時間がかかります)
